'use client'

import { motion } from 'framer-motion'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { Button } from '@/components/ui/button'
import { DollarSign, TrendingUp, Users, Shield, CheckCircle, ArrowRight } from 'lucide-react'
import Link from 'next/link'

export default function AffiliatePage() {
	return (
		<div className="min-h-screen bg-background">
			<Header />
			<main className="pt-32 md:pt-36 pb-16">
				<div className="container mx-auto px-6">
					{/* Page Header */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						className="text-center mb-16"
					>
						<span className="text-xs uppercase tracking-[0.2em] text-muted-foreground mb-4 block font-sans">
							Affiliate Program
						</span>
						<h1 className="font-serif text-4xl md:text-5xl font-medium mb-4">
							Become an Enhanced Chem Affiliate
						</h1>
						<p className="text-muted-foreground max-w-2xl mx-auto text-lg">
							Earn commission by referring customers to Enhanced Chem&apos;s lab-grade research products. 
							Once approved, you&apos;ll receive a unique referral link to share across your website, social media, or content.
						</p>
					</motion.div>

					{/* Benefits Grid */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.1 }}
						className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-6 mb-16"
					>
						<div className="bg-card rounded-lg border border-border p-3 md:p-6 text-center">
							<div className="bg-primary/10 w-12 h-12 md:w-16 md:h-16 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
								<DollarSign className="w-6 h-6 md:w-8 md:h-8 text-primary" />
							</div>
							<h3 className="font-serif text-xs md:text-xl font-medium mb-1.5 md:mb-2">
								Competitive Commissions
							</h3>
							<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
								25% commission on every sale made through your unique referral link or code
							</p>
						</div>

						<div className="bg-card rounded-lg border border-border p-3 md:p-6 text-center">
							<div className="bg-primary/10 w-12 h-12 md:w-16 md:h-16 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
								<Users className="w-6 h-6 md:w-8 md:h-8 text-primary" />
							</div>
							<h3 className="font-serif text-xs md:text-xl font-medium mb-1.5 md:mb-2">
								Personalized Coupon
							</h3>
							<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
								10% off for your audience to help increase conversions
							</p>
						</div>

						<div className="bg-card rounded-lg border border-border p-3 md:p-6 text-center">
							<div className="bg-primary/10 w-12 h-12 md:w-16 md:h-16 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
								<TrendingUp className="w-6 h-6 md:w-8 md:h-8 text-primary" />
							</div>
							<h3 className="font-serif text-xs md:text-xl font-medium mb-1.5 md:mb-2">
								Second-Tier Earnings
							</h3>
							<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
								Earn 5% of all sales generated by affiliates you personally refer to Enhanced Chem
							</p>
						</div>

						<div className="bg-card rounded-lg border border-border p-3 md:p-6 text-center">
							<div className="bg-primary/10 w-12 h-12 md:w-16 md:h-16 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
								<Shield className="w-6 h-6 md:w-8 md:h-8 text-primary" />
							</div>
							<h3 className="font-serif text-xs md:text-xl font-medium mb-1.5 md:mb-2">
								Transparent Tracking &amp; Payouts
							</h3>
							<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
								Clear reporting and monthly payouts. No upfront cost — join free and start earning after approval.
							</p>
						</div>
					</motion.div>

					{/* How It Works */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.2 }}
						className="bg-card rounded-lg border border-border p-8 md:p-12 mb-16"
					>
						<h2 className="font-serif text-3xl font-medium mb-8 text-center">How It Works</h2>
						<div className="grid grid-cols-3 gap-3 md:gap-8">
							<div className="text-center">
								<div className="bg-primary/10 w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
									<span className="text-primary font-bold text-sm md:text-xl">1</span>
								</div>
								<h3 className="font-serif text-xs md:text-lg font-medium mb-1.5 md:mb-2">
									Apply &amp; Get Approved
								</h3>
								<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
									Submit your application with your website or social media details. Approval is typically within 1–2 business days.
								</p>
							</div>

							<div className="text-center">
								<div className="bg-primary/10 w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
									<span className="text-primary font-bold text-sm md:text-xl">2</span>
								</div>
								<h3 className="font-serif text-xs md:text-lg font-medium mb-1.5 md:mb-2">
									Get Your Link &amp; Coupon Code
								</h3>
								<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
									Once approved, you&apos;ll receive a unique referral link and a personalized coupon code (10% off for your audience) to share across any platform.
								</p>
							</div>

							<div className="text-center">
								<div className="bg-primary/10 w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center mx-auto mb-3 md:mb-4">
									<span className="text-primary font-bold text-sm md:text-xl">3</span>
								</div>
								<h3 className="font-serif text-xs md:text-lg font-medium mb-1.5 md:mb-2">
									Earn Commissions
								</h3>
								<p className="text-muted-foreground text-[10px] md:text-sm leading-snug">
									Earn 25% on every sale through your referral link or code. Earn an additional 5% on all sales from affiliates you refer. Payments are made monthly via PayPal, CashApp, or Venmo.
								</p>
							</div>
						</div>
					</motion.div>

					{/* Requirements */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.3 }}
						className="bg-secondary/50 rounded-lg border border-border p-8 mb-16"
					>
						<h2 className="font-serif text-2xl font-medium mb-6 text-center">Program Requirements</h2>
						<div className="grid md:grid-cols-2 gap-6 max-w-3xl mx-auto">
							<div className="flex items-start gap-3">
								<CheckCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
								<div>
									<h3 className="font-medium mb-1">21+ Years Old</h3>
									<p className="text-sm text-muted-foreground">Must be at least 21 years of age</p>
								</div>
							</div>
							<div className="flex items-start gap-3">
								<CheckCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
								<div>
									<h3 className="font-medium mb-1">Professional Platform</h3>
									<p className="text-sm text-muted-foreground">Website, blog, or social media presence</p>
								</div>
							</div>
							<div className="flex items-start gap-3">
								<CheckCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
								<div>
									<h3 className="font-medium mb-1">Compliance</h3>
									<p className="text-sm text-muted-foreground">Must comply with all program terms and guidelines</p>
								</div>
							</div>
							<div className="flex items-start gap-3">
								<CheckCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
								<div>
									<h3 className="font-medium mb-1">Payment Method</h3>
									<p className="text-sm text-muted-foreground">PayPal, CashApp, or Venmo account required</p>
								</div>
							</div>
						</div>
					</motion.div>

					{/* Affiliate Dashboard Section */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.4 }}
						className="mb-16"
					>
						<div className="bg-card rounded-lg border border-border p-8 md:p-12 max-w-3xl mx-auto">
							<h2 className="font-serif text-3xl font-medium mb-6 text-center">Affiliate Dashboard</h2>
							<p className="text-muted-foreground text-center mb-6">
								If you are not an affiliate yet, please{' '}
								<a 
									href="https://www.affiliatly.com/af-1074129/affiliate.panel?mode=register" 
									target="_blank" 
									rel="noopener noreferrer"
									className="text-primary hover:underline font-medium"
								>
									click here and apply
								</a>
								.
							</p>
							<div className="text-center">
								<a
									href="https://www.affiliatly.com/af-1074129/affiliate.panel"
									target="_blank"
									rel="noopener noreferrer"
								>
									<Button variant="elegant" size="lg" className="gap-2">
										Access Affiliate Dashboard
										<ArrowRight className="w-4 h-4" />
									</Button>
								</a>
							</div>
						</div>
					</motion.div>

					{/* CTA Section */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.5 }}
						className="text-center"
					>
						<div className="bg-primary/5 rounded-lg border-2 border-primary/20 p-8 md:p-12 max-w-2xl mx-auto">
							<Shield className="w-12 h-12 text-primary mx-auto mb-4" />
							<h2 className="font-serif text-3xl font-medium mb-4">Ready to Get Started?</h2>
							<p className="text-muted-foreground mb-8 max-w-xl mx-auto">
								Join our affiliate program today and start earning commissions by promoting premium research peptides to qualified researchers.
							</p>
							<a
								href="https://www.affiliatly.com/af-1074129/affiliate.panel?mode=register"
								target="_blank"
								rel="noopener noreferrer"
							>
								<Button variant="elegant" size="lg" className="gap-2">
									Apply to Become an Affiliate
									<ArrowRight className="w-4 h-4" />
								</Button>
							</a>
						</div>
					</motion.div>

					{/* Important Notes */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.5 }}
						className="mt-16 bg-red-50 border-2 border-red-200 rounded-lg p-6 max-w-3xl mx-auto"
					>
						<h3 className="font-semibold text-red-900 mb-3">Important Program Guidelines</h3>
						<ul className="space-y-2 text-sm text-red-800">
							<li className="flex items-start gap-2">
								<span className="font-bold">•</span>
								<span>All products are for scientific research purposes only. Not for human or animal consumption.</span>
							</li>
							<li className="flex items-start gap-2">
								<span className="font-bold">•</span>
								<span>Commissions are paid monthly when the minimum threshold of $100 is met.</span>
							</li>
							<li className="flex items-start gap-2">
								<span className="font-bold">•</span>
								<span>All promotional materials must comply with our terms and guidelines. Violations may result in immediate termination.</span>
							</li>
							<li className="flex items-start gap-2">
								<span className="font-bold">•</span>
								<span>For questions or support, contact us at <a href="mailto:contact@enhancedchem.com" className="underline">contact@enhancedchem.com</a></span>
							</li>
						</ul>
					</motion.div>
				</div>
			</main>
			<Footer />
		</div>
	)
}
